language: java
jdk:
  - openjdk17

install: true
dist: jammy
os:
  - linux

services:
  - postgresql
before_install:
  - chmod +x mvnw
  - psql -c 'create database todo;' -U postgres

script:
  # JaCoCo is used to have code coverage, "-Pcoverage" activates the maven profile in the pom.xml

cache:
  directories:
    - '$HOME/.m2/repository'

## после выполнени¤ сборки запустить скрипт, который будет собирать статистику по JaCoCo
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - bash <(curl -Ls https://coverage.codacy.com/get.sh)
  #  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r target/jacoco/jacoco.xml
  - mvn clean test jacoco:report coveralls:report

# отправл¤ть уведомление на почту youremail@smtp.ru(»зменить на свою) если сборка упала
notifications:
  webhooks: https://coveralls.io/webhook
  email:
    recipients: "-123mib@gmail.com"
    on_success: always # default: change
    on_failure: always # default: always

env:
  global:
    - CODECOV_TOKEN="2c78f3ea-60cd-4abb-afe3-0c0e5143c070"