CREATE TABLE IF NOT EXISTS category
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(40),
    CONSTRAINT pk_category PRIMARY KEY (id)
);

create table IF NOT EXISTS item_category
(
    item_id bigint not null references item(id),
    categories_id bigint not null references category(id),
    primary key (item_id, categories_id)
);
