drop table if exists item;
CREATE TABLE IF NOT EXISTS item
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    description VARCHAR(255),
    created     date,
    status      BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_item PRIMARY KEY (id)
);

drop table if exists account;
CREATE TABLE IF NOT EXISTS account
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    login    VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT pk_account PRIMARY KEY (id)
);
